// glossaryファイル Command_prompt
`use strict`
const glossary = [
{target:`mkdir`, content:`ディレクトリを作成する。<br>$ *** test_npm`},
{target:`cd`, content:`ディレクトリの内容を表示する。<br>$ *** test_npm`},
{target:`echo`, content:`任意の文字列を画面に表示。<br>$ *** '{ 'private': true }' >> package.json`},
{target:`>>`, content:`echo コマンドの出力を package.json ファイルの末尾に追加。<br>$ echo '{ 'private': true }' *** package.json`},
{target:`cat`, content:`ファイルの内容を表示する。<br>$ *** package.json → { 'private': true }`},
{target:`rd`, content:`ディレクトリを削除する。<br>$ *** -rf node_modules`},
{target:`dir`, content:`ディレクトリの内容を表示する。<br>$ ***`},
{target:`curl`, content:`コマンドラインからデータをURLを介して転送するためのツール。ウェブサーバーへのリクエストやAPIのテストなどに広く使用。<br>$ *** http://example.com → 指定したURLコンテンツを取得`},
{target:`attrib`, content:`ファイル属性の表示と設定。<br>$ attrib +r example.txt`},
{target:`md / mkdir`, content:`ディレクトリを作成。<br>$ mkdir NewFolder`},
{target:`rd / rmdir`, content:`ディレクトリを削除。<br>$ rmdir OldFolder`},
{target:`tree`, content:`フォルダ構造を図式表示。<br>$ tree`},
{target:`copy`, content:`ファイルをコピー。<br>$ copy file1.txt C:\Backup\ `},
{target:`del`, content:`ファイルを削除。<br>$ del unwantedfile.txt`},
{target:`find`, content:`ファイルの中からテキストを検索。<br>$ find 'text' example.txt`},
{target:`findstr`, content:`文字列や正規表現を使って検索。<br>$ findstr 'pattern' example.txt`},
{target:`more`, content:`ファイルの内容をページごとに表示。<br>$ more example.txt`},
{target:`move`, content:`ファイルの移動・名称変更。<br>$ move file.txt C:\NewFolder\ `},
{target:`ren / rename`, content:`ファイル名・ディレクトリ名を変更。<br>$ ren oldname.txt newname.txt`},
{target:`replace`, content:`ファイルを置き換える。<br>$ replace newfile.txt C:\OldFolder`},
{target:`robocopy`, content:`ファイルやフォルダをコピー。<br>$ robocopy C:\Source C:\Dest`},
{target:`sort`, content:`データを並べ替える。<br>$ sort example.txt`},
{target:`type`, content:`ファイルの内容を表示。<br>$ type example.txt`},
{target:`where`, content:`ファイルを検索。<br>$ where notepad.exe`},
{target:`tasklist`, content:`実行中プロセスの一覧表示。<br>$ tasklist`},
{target:`taskkill`, content:`指定したタスクの終了。<br>$ taskkill /IM notepad.exe`},
{target:`date`, content:`日付を表示・設定。<br>$ date /T`},
{target:`help`, content:`コマンドのヘルプを表示。<br>$ help copy`},
{target:`hostname`, content:`ホスト名を表示。<br>$ hostname`},
{target:`systeminfo`, content:`システム構成情報を表示。<br>$ systeminfo`},
{target:`time`, content:`時刻を表示・設定。<br>$ time /T`},
{target:`ver`, content:`Windowsのバージョンを表示。<br>$ ver`},
{target:`whoami`, content:`ログイン中ユーザの情報を表示。<br>$ whoami`},
{target:`clip`, content:`コマンドの出力をクリップボードにコピー。<br>$ 'echo Hello`},
{target:`cls`, content:`画面をクリア。<br>$ cls`},
{target:`cmd`, content:`新しいコマンドプロンプトを起動。<br>$ cmd`},
{target:`exit`, content:`コマンドプロンプトを終了。<br>$ exit`},
{target:`prompt`, content:`コマンドプロンプトを変更。<br>$ prompt $P$G`},
{target:`start`, content:`新規コマンドプロンプトを開く。<br>$ start cmd`},
{target:`shutdown`, content:`シャットダウン/再起動/ログオフ。<br>$ shutdown /s`},
{target:`ftp`, content:`ファイルを転送。<br>$ ftp example.com`},
{target:`getmac`, content:`MACアドレスを表示。<br>$ getmac`},
{target:`nbtstat`, content:`NetBIOSの状態を表示。<br>$ nbtstat -a`},
{target:`net`, content:`ネットワーク操作。<br>$ net user`},
{target:`netstat`, content:`ネットワーク統計を表示。<br>$ netstat -an`},
{target:`nslookup`, content:`DNSサーバを問い合わせる。<br>$ nslookup example.com`},
{target:`pathping`, content:`経路の追跡と統計を表示。<br>$ pathping example.com`},
{target:`ping`, content:`ネットワークの疎通を確認。<br>$ ping example.com`},
{target:`pathpping/ tracert`, content:`ネットワークの経路を追跡。<br>$ tracert example.com`},
{target:`tracert`, content:`ネットワークの経路を確認。<br>$ tracert www.example.com`},
{target:`call`, content:`バッチファイルを呼び出す。<br>$ call script.bat`},
{target:`choice`, content:`ユーザー入力を受付ける。<br>$ choice /M 'Yes or No?'`},
{target:`cscript`, content:`スクリプトファイルを実行。<br>$ cscript script.vbs`},
{target:`endlocal`, content:`環境変数のローカル化を終了。<br>$ endlocal`},
{target:`for`, content:`ループ処理を実行。<br>$ for %i in (*) do @echo %i`},
{target:`if`, content:`条件処理を行う。<br>$ if exist file.txt echo found`},
{target:`pause`, content:`処理を一時停止。<br>$ pause`},
{target:`rem`, content:`コメントを記述。<br>$ rem This is a comment`},
{target:`comp`, content:`2つのファイルをバイナリ比較。<br>$ comp file1.txt file2.txt`},
{target:`fc`, content:`2つのファイルを比較して違いを表示。<br>$ fc file1.txt file2.txt`},
{target:`print`, content:`テキストファイルを印刷。<br>$ print /D:LPT1 example.txt`},
{target:`recover`, content:`欠陥ディスクからファイルを回復。<br>$ recover lostfile.txt`},
{target:`xcopy`, content:`ファイルをディレクトリ構造ごとコピー。<br>$ xcopy C:\Source C:\Dest /E`},
{target:`chkdsk`, content:`ディスクの状態をチェック。<br>$ chkdsk C:`},
{target:`chkntfs`, content:`起動時のディスクチェックを設定。<br>$ chkntfs /D`},
{target:`defrag`, content:`ディスクを最適化。<br>$ defrag C:`},
{target:`label`, content:`ボリュームラベルを作成・変更・削除。<br>$ label C: MyLabel`},
{target:`vol`, content:`ディスクのボリュームラベルを表示。<br>$ vol C:`},
{target:`at`, content:`プログラム・コマンドの実行予約。<br>$ at 12:00 notepad.exe`},
{target:`assoc`, content:`拡張子の関連付けの表示・設定。<br>$ assoc .txt=txtfile`},
{target:`set`, content:`環境変数を表示・設定。<br>$ set PATH`},
{target:`subst`, content:`ドライブ名を割当て/解除。<br>$ subst Z: C:\Folder`},
{target:`chcp`, content:`コンソールの文字コード表示/設定。<br>$ chcp 65001`},
{target:`title`, content:`ウィンドウのタイトルを設定。<br>$ title MyTitle`},
{target:`runas`, content:`別ユーザの権限でプログラムを実行。<br>$ runas /user:Admin cmd`},
{target:`ipconfig`, content:`ネットワーク設定を確認。<br>$ ipconfig`},
{target:`logoff`, content:`セッションを終了。<br>$ logoff`},
{target:`route`, content:`ルーティングテーブルを表示/編集。<br>$ route print`},
{target:`setlocal`, content:`環境変数のローカル化を開始。<br>$ setlocal`},
{target:`shift`, content:`コマンドライン引数をシフト。<br>$ shift`},
{target:`timeout`, content:`一定時間待機。<br>$ timeout /T 10`},
{target:`convert`, content:`ファイルシステムを変換。<br>$ convert C: /FS:NTFS`},
{target:`eventcreate`, content:`イベントログを作成。<br>$ eventcreate /ID 1 /L APPLICATION /T INFORMATION /SO MySource /D 'Event Description'`},
{target:`format`, content:`ディスクをフォーマット。<br>$ format C:`},
{target:`path`, content:`ファイル・プログラムのディレクトリを表示/設定。<br>$ path C:\Windows\System32`},
{target:`cacls`, content:`アクセス権を設定・表示。<br>$ cacls example.txt /G Username:F`},
{target:`ftype`, content:`拡張子に関連したアプリケーションを設定。<br>$ ftype txtfile=C:\Program.exe %1`},
{target:`schtasks`, content:`タスクの作成/変更/削除/照会。<br>$ schtasks /Create /SC daily /TN Backup /TR backup.bat`},
{target:`sc`, content:`サービスに関設定・確認。<br>$ sc query`},
{target:`setx`, content:`環境変数を永続設定。<br>$ setx PATH 'C:\NewPath'`},
{target:`color`, content:`コンソールの色を設定。<br>$ color 0A`},
{target:`doskey`, content:`コマンドのマクロを定義。<br>$ doskey ls=dir`},
{target:`arp`, content:`ARPキャッシュを表示/編集。<br>$ arp -a`},
{target:`bootcfg`, content:`ブート構成を編集。<br>$ bootcfg /rebuild`},
]
